[tool.poetry]
name = "html_codegen"
version = "0.1.0"
description = ""
authors = ["AndrewBalakirev <balakirev.andrei.it@gmail.com>"]
readme = "README.md"
packages = [{include = "html_codegen"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
brython = "^3.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
